name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env.test file
        - name: Create .env.test file
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env.test
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env.test
          echo "DB_USER=${{ vars.DB_USER }}" >> .env.test
          echo "DB_PASSWORD=${{ vars.DB_PASSWORD }}" >> .env.test
          echo "DB_NAME=${{ vars.DB_NAME }}" >> .env.test
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env.test
          echo "PORT=${{ vars.PORT }}" >> .env.test

      - name: Run tests
        run: npm test
